//I hope to add more quotes later
var quoteList = ['"Time flies like an arrow; fruit flies like a banana." </br>-linguistics adage',
	'"There are 10 types of people: those who know binary code and those who don’t." </br>-Unknown',
	'"Long separated by cruel fate, the star-crossed lovers raced across the grassy field toward each other like two freight trains, one having left Cleveland at 6:36pm traveling at 55 mph, the other from Topeka at 4:19pm at a speed of 35 mph." </br>-Jennifer Hart, for <a href="http://www.washingtonpost.com/wp-dyn/content/article/2007/03/16/AR2007031600802.html" target="_blank">this</a> contest',
	'"The Fibonacci sequence: easy as 1, 1, 2, 3!" </br>-Unknown',
	'"Like, don\'t be a prescriptivist!" </br>-linguistics classmate',
	'"A user interface is like a joke. If you have to explain it, it\'s not that good." </br>-Unknown',
	'"In order to understand recursion, you must understand recursion." </br>-computer science proverb',
	'"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo." </br>-Dmitri Borgmann',
	'"Ah, numbers. The letters of math." </br>-John Mulaney',
	'"As the saying goes, \'Sticks and stones may break my bones, but words are merely the smallest element of language containing meaning in isolation and as such could never directly produce the 4,000 Newtons of force per square centimeter required to break bones.\'" </br>-Vsauce',
	'"I\'d give a right arm to become ambidextrous." </br>-Unknown',
	'"Don\'t drink and derive. Alcohol and calculus don\'t mix." </br>-Unknown',
	'"43.1% of all statistics are made up on the spot." </br>-Unknown',
	'"Metaphors be with you." </br>-Unknown',
	'"Gravity always gets me down." </br>-Anonymous',
	'"He was as tall as a six-foot-three-inch tree." </br>-Jack Bross, for <a href="http://www.washingtonpost.com/wp-dyn/content/article/2007/03/16/AR2007031600802.html" target="_blank">this</a> contest',
	'"Etc: a sign to make others believe that you know more than you actually do." </br>-Anonymous',
	'"We\'ll have a plosive party. It\'ll end with a bang!" </br>-linguistics classmate',
	'"Give me ambiguity or give me something else!" </br>-Anonymous',
	'"The best angle to approach any problem is the try-angle." </br>-Unknown',
	'"If you succeeded at failing, did you succeed or fail?" </br>-Unknown',
	'"Asking a linguist \'How many languages do you speak?\' is like asking a doctor \'How many diseases do you have?\'" </br>-Unknown',
	'"Be like a schwa. It\'s never stressed." </br>-Unknown',
	'"As the saying goes, \'Sticks and stones may break my bones, but words are merely the smallest element of language containing meaning in isolation and as such could never directly produce the 4,000 Newtons of force per square centimeter required to break bones.\'" </br>-Vsauce',
	'"Give me ambiguity or give me something else!" </br>-Anonymous',
	'"The future isn\'t what it used to be." </br>-Unknown',
	'"Code never lies. Comments sometimes do." </br>-Anonymous',
	'"In order to understand recursion, you must understand recursion." </br>-computer science proverb',
	'"Haikus are easy</br>But sometimes they don\'t make sense</br>Refrigerator"</br></br>-Unknown',
	'"Metaphors be with you." </br>-Unknown',
	'"Corduroy pillows make headlines." </br>-Anonymous',
	'"If you\'re reading this quote, either I\'m not as good at JavaScript as I thought or something rather strange is happening." </br>-Elizabeth Lee']
var d = new Date();
document.getElementById("quote").innerHTML = quoteList[d.getDate()-1];